# Microservice: ms-account-reservation
# Task: UPGGA-1 Create Application Skeleton

spring:
  application:
    name: ${app.name}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  liquibase:
     enabled: true
     change-log: classpath:db/changelog/db-changelog-master.yml
     default-schema: public

server:
  port: ${app.port}