spring:
  application:
    name: ${APP_NAME}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
     enabled: true
     change-log: classpath:db/changelog/db-changelog-master.yml
     default-schema: public

server:
  port: ${APP_PORT}

management:
  server:
    port: ${APP_SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: health, info, threaddump