#spring.application.name=ms-account-reservation
app.name=ms-account-reservation
app.port=8080
app.server.port=8081
db.url=jdbc:postgresql://localhost:5432/account_reservation?currentSchema=public
db.username=postgres
db.password=password